---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  APP_CORS_ALLOW_ORIGIN: {{ .Values.app.cors_allow_origin | quote }}
  APP_TRUSTED_PROXIES: {{ .Values.app.trusted_proxies | quote }}
  APP_SOURCE_BASE: {{ .Values.app.source.base | quote }}
  APP_SOURCE_SEARCH_FEED: {{ .Values.app.source.feed | quote }}
  APP_SOURCE_AUTO_DATA: {{ .Values.app.source.autodata | quote }}
  APP_DATABASE_URL: {{ .Values.app.db.url | quote }}
  APP_DESTINATION_DIRECTORY: {{ .Values.app.destination.directory | quote }}
  PHP_PM_MAX_CHILDREN: {{ .Values.app.php.max_children | quote }}
  PHP_PM_START_SERVERS: {{ .Values.app.php.start_servers | quote }}
  PHP_PM_MIN_SPARE_SERVERS: {{ .Values.app.php.min_spare_servers | quote }}
  PHP_PM_MAX_SPARE_SERVERS: {{ .Values.app.php.max_spare_servers | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-nginx-config
data:
  APP_PATH_PREFIX: {{ .Values.ingress.path | quote }}
  PHP_FPM_SERVER: "127.0.0.1"
  PHP_FPM_SERVER_PORT: "9000"
